#!/bin/bash

find . -type d -exec sudo chmod 775 {} \;
find . -type f -name '*.php' -exec sudo chmod 664 {} \;
find . -type f -name '*.css' -exec sudo chmod 664 {} \;
find . -type f -name '*.js' -exec sudo chmod 664 {} \;
sudo chown www-data:www-data -R /var/www
